cargo update: addresses 'cargo audit' error regarding RUSTSEC-2024-0003
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 604 security advisories (from /home/mark-despain/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (251 crate dependencies)
Crate:     h2
Version:   0.3.21
Title:     Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
Date:      2024-01-17
ID:        RUSTSEC-2024-0003
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0003
Solution:  Upgrade to ^0.3.24 OR >=0.4.2
Dependency tree:
h2 0.3.21
├── reqwest 0.11.22
│   └── oidc-authorizer 0.0.4
└── hyper 0.14.27
    ├── reqwest 0.11.22
    ├── lambda_runtime_api_client 0.8.0
    │   └── lambda_runtime 0.8.2
    │       └── oidc-authorizer 0.0.4
    ├── lambda_runtime 0.8.2
    ├── hyper-rustls 0.24.1
    │   └── reqwest 0.11.22
    └── httpmock 0.6.8
        └── oidc-authorizer 0.0.4

error: 1 vulnerability found!